version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog-rest-api
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  db-data: