name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          chmod +x mvnw
          ./mvnw clean install -DskipTests

      - name: Build and run Docker Compose
        run: |
          docker-compose up --build -d
        env:
          SPRING_PROFILES_ACTIVE: default
          DATABASE_URL: jdbc:postgresql://postgres:5432/blog-rest-api
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
