name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          chmod +x mvnw
          ./mvnw clean install -DskipTests

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build and run Docker Compose
        run: |
          docker-compose up --build -d
          docker-compose ps
        env:
          SPRING_PROFILES_ACTIVE: default
          DATABASE_URL: jdbc:postgresql://postgres:5432/blog-rest-api
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
